// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy3XEom5ct9fuMu9Z4lXVVqoYhuu6JOgY',
    appId: '1:600163443309:web:7068ee5201e34ddfcbd564',
    messagingSenderId: '600163443309',
    projectId: 'collegecounsel24935',
    authDomain: 'collegecounsel24935.firebaseapp.com',
    storageBucket: 'collegecounsel24935.appspot.com',
    measurementId: 'G-XFM9C0P2HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC04OLk2-l84krq63KQhzhvG9y-NDuPT1M',
    appId: '1:600163443309:android:1974074079c525b3cbd564',
    messagingSenderId: '600163443309',
    projectId: 'collegecounsel24935',
    storageBucket: 'collegecounsel24935.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCUB8eFvuGnKJMv4F3Z-jNfYja8ljrYWg',
    appId: '1:600163443309:ios:9833975f2acebc89cbd564',
    messagingSenderId: '600163443309',
    projectId: 'collegecounsel24935',
    storageBucket: 'collegecounsel24935.appspot.com',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCUB8eFvuGnKJMv4F3Z-jNfYja8ljrYWg',
    appId: '1:600163443309:ios:9833975f2acebc89cbd564',
    messagingSenderId: '600163443309',
    projectId: 'collegecounsel24935',
    storageBucket: 'collegecounsel24935.appspot.com',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy3XEom5ct9fuMu9Z4lXVVqoYhuu6JOgY',
    appId: '1:600163443309:web:b1e03ae46a114477cbd564',
    messagingSenderId: '600163443309',
    projectId: 'collegecounsel24935',
    authDomain: 'collegecounsel24935.firebaseapp.com',
    storageBucket: 'collegecounsel24935.appspot.com',
    measurementId: 'G-TBF67YRK88',
  );
}
